### ISSUE TITLE
mapping category id to class name seadronesee

### ISSUE THREAD

**Issue by fabiopoiesi** [Eisbaer8/DeepGTAV#6]
What is the mapping between category id and the class name?
I am using the same one as that of Seadronesee (real) but it seems not working.

This is the one taken from Seadronesee:

![Screenshot from 2022-05-23 11-40-29](https://user-images.githubusercontent.com/17005352/169791413-1d683aab-0ef4-4a99-9a7c-22b4e81c0ff3.png)

Thanks

**Comment by C-der-Baum** [comment]
If I remember correctly, the mapping is as follows:

{"swimmer": 0, "floater": 1, "swimmer on boat": 2, "floater on boat": 3, "boat":4}

I'll add it to the readme.

**Comment by fabiopoiesi** [comment]
lifejacket?

**Comment by C-der-Baum** [comment]
There is no life jacket class (and no images containing just life jackets) in the synthetic version. In the paper (leveraging synthetic...), we still considered the class "life jacket" when evaluating on SeaDronesSee. However, it is very much underrepresented in the data set which is why standard object detectors fail on this class, yielding almost 0 AP (as can be seen in the SeaDronesSee paper). Therefore, it does not hurt in our Sim2real experiments to just ignore that class during training entirely.

**Comment by fabiopoiesi** [comment]
Thanks!
